services:
  web:
    build: .
    image: aaronbengo/cca2:latest
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cca2
      - MONGO_COLLECTION=todo


  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo-data:
