version: '3.8'

services:
  web:
    build: .
    image: aaronbengo/cca2:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo_db
      - PORT=3000

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
