apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 0  # Specify the desired number of replicas
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: aaronbengo/cca2:latest
        ports:
        - containerPort: 3000
        env:
        - name: FLASK_ENV
          value: "development"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/todo_db"
        - name: PORT
          value: "3000"
