apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer    # Change from NodePort to LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 3000          # Service port
    targetPort: 3000    # Container port