apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: taskpad
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer