apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: taskpad
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         # Allows for x unavailable pods on update
      maxUnavailable: 1   # Allows for x extra pods on update
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: aaronbengo/taskpad:latest
        ports:
        - name: flask-http-port
          containerPort: 3000
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "cca2"
        - name: MONGO_COLLECTION
          value: "todo"
        livenessProbe:
          httpGet:
            path: /health # Uses HTTP get to check health status of app
            port: flask-http-port
          initialDelaySeconds: 15 # Waits x seconds after pod creation before begining
          periodSeconds: 15       # Checks every X seconds
          failureThreshold: 3     # Amount of consecutive failures before k8 restarts the pod
        readinessProbe:
          httpGet:
            path: /health 
            port: flask-http-port
          initialDelaySeconds: 15 
          periodSeconds: 10 
          failureThreshold: 3 
