apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: taskpad
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001