apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: aaronbengo/cca2:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "cca2"
        - name: MONGO_COLLECTION
          value: "todo"
