apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: taskpad
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 40001