alertmanager:
  config:
    global:
      slack_api_url: "https://hooks.slack.com/services/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"
    route:
      group_by: ['alertname']            # grouping keys (adjust as needed)
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-notifications      # send all alerts to Slack by default
      routes:
        - matchers:
            - alertname = "Watchdog"     # drop the Watchdog heartbeat alert
          receiver: null
    receivers:
      - name: "null"
      - name: "slack-notifications"
        slack_configs:
          - channel: "#test"        # Slack channel for alerts
            send_resolved: true
            # Optional: title, text, etc., or rely on Alertmanager defaults/templates
